ProjetASPCore/Controllers/BookController.cs
using Microsoft.AspNetCore.Mvc;
using ProjetASPCore.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ProjetASPCore.Controllers
{
    public class BookController : Controller
    {
        private readonly IBookRepository _bookRepository;
        private readonly ICategoryRepository _categoryRepository;

        public BookController(IBookRepository bookRepository, ICategoryRepository categoryRepository)
        {
            _bookRepository = bookRepository;
            _categoryRepository = categoryRepository;
        }

        public IActionResult List()
        {
            var bookListViewModel = new BookListViewModel();
            bookListViewModel.Books = _bookRepository.GetAllBooks();
            return View(bookListViewModel);
        }

        public IActionResult Details(int idBook)
        {
            var book = _bookRepository.GetBookById(idBook);
            if (book == null)
                return NotFound();
            else
                return View(book);
        }
    }
}

ProjetASPCore/Controllers/ShoppingCardController.cs
using Microsoft.AspNetCore.Mvc;
using ProjetASPCore.Models;
using ProjetASPCore.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ProjetASPCore.Controllers
{
    public class ShoppingCartController : Controller
    {
        private readonly IBookRepository _bookRepository;
        private readonly ShoppingCart _shoppingCart;

        public ShoppingCartController(IBookRepository bookeRepository, ShoppingCart shoppingCart)
        {
            _bookRepository = bookeRepository;
            _shoppingCart = shoppingCart;
        }
        public IActionResult Index()
        {
            var items = _shoppingCart.GetShoppingCartItems();
            _shoppingCart.ShoppingCartItems = items;
            var shoppingCartViewModel = new ShoppingCartViewModel();
            shoppingCartViewModel.ShoppingCart = _shoppingCart;
            shoppingCartViewModel.ShoppingCartTotal = _shoppingCart.GetShoppingCartTotal();
            return View(shoppingCartViewModel);
        }
        public RedirectToActionResult AddToShoppingCart(int idBook)
        {
            var book = _bookRepository.GetBookById(idBook);
            if (book != null)
            {
                _shoppingCart.AddToCart(book, 1);
            }
            return RedirectToAction("Index");
        }
        public RedirectToActionResult RemoveFromShoppingCart(int idBook)
        {
            var book = _bookRepository.GetBookById(idBook);
            if (book != null)
            {
                _shoppingCart.RemoveFromCart(book);
            }
            return RedirectToAction("Index");
        }
    }
}

ProjetASPCore/Views/shared/_CardBook.cshtml
@model Book

<div class="col-sm-4 col-lg-4 col-md-4">
    <div class="thumbnail">
        <h2>
            <a asp-controller="Book" asp-action="Detail" asp-route-idBook="@Model.BookId">@Model.Name</a>
        </h2>
        <img src="@Model.ImageUrl" alt="" width="150" height="400">
        <div class="caption">
            <p>@Model.ShortDescription</p>
            <h3 class="pull-right">@Model.Price.ToString("c")</h3>
        </div>
        <div class="addToCart">
            <p class="button">
                <a class="btn btn-primary" asp-controller="ShoppingCart" asp-action="AddToShoppingCart" asp-route-idBook="@Model.BookId"> Add to Cart</a>
            </p>
        </div>
    </div>
</div>

ProjetASPCore/Views/shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Le site E-commerce Library</title>
    <link href="~/Lib/bootstrap/css/bootstrap.css" rel="stylesheet" />
    <script src="~/Lib/jquery/jquery.js"></script>
    <script src="~/Lib/bootstrap/js/bootstrap.js"></script>
    <link href="~/contents/site.css" rel="stylesheet" />

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">


</head>
<body>
    <div class="container">
        <nav class="navbar navbar-expand-sm bg-primary navbar-dark">
            <div class="container-fluid">
                <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
                    <div class="navbar-nav">
                        <a class="nav-link active" asp-controller="Home" asp-action="Index">Home</a>
                        <a class="nav-link active" asp-controller="Book" asp-action="List">Books</a>
                        @await Component.InvokeAsync("ShoppingCartSummary")
                        <a class="nav-item nav-link active" asp-controller="Contact" asp-action="Index">Contact</a>
                        <partial name="_LoginPartial" />
                    </div>
                </div>
            </div>
        </nav>
        <div class="row">
            @RenderBody()
        </div>
        @RenderSection("Scripts", required: false)
    </div>
</body>
</html>